name: Test240
favicon: null
layout_spectrum: 0.39237991883419454
typography_spectrum: 0.7400674188975245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5074569191783667
  lightness: 0.460200221510604
  saturation: 0.36205727769993246
  rhythmicContrast: 0.8031589651945978
purpose: []
